from pathlib import Path
import json
import zipfile
import re

try:
    import yaml
except ImportError:
    raise SystemExit("Please install PyYAML: pip install pyyaml")

ROOT = Path(__file__).resolve().parents[1]

CONFIG_DIR = ROOT / "config" / "course_factory"
CONTENT_DIR = ROOT / "content" / "courses"
EXPORT_ROOT = ROOT / "exports" / "course_factory"

EXPORT_ROOT.mkdir(parents=True, exist_ok=True)


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def lesson_html(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{title}</title>
<style>
body {{
  font-family: Arial, sans-serif;
  max-width: 900px;
  margin: 40px auto;
  line-height: 1.6;
  padding: 0 16px;
}}
h1, h2, h3 {{ line-height: 1.2; }}
.lesson-meta {{
  color: #555;
  margin-bottom: 24px;
}}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="lesson-meta">Generated by Arkansas Civics Course Factory</div>
<div>{body.replace(chr(10), "<br>")}</div>
</body>
</html>
"""


def build_rise_ai_import(course_config: dict, lessons: list[dict]) -> str:
    parts = []
    parts.append(f"COURSE TITLE: {course_config['title']}")
    parts.append(f"COURSE SUBTITLE: {course_config.get('subtitle', '')}")
    parts.append(f"COURSE DESCRIPTION: {course_config.get('description', '')}")
    parts.append("")

    for idx, lesson in enumerate(lessons, start=1):
        parts.append(f"LESSON {idx}: {lesson['title']}")
        parts.append("")
        parts.append("LESSON OBJECTIVE:")
        parts.append("Learners will understand and apply the main civic concepts in this lesson.")
        parts.append("")
        parts.append("LESSON CONTENT:")
        parts.append(lesson["body"])
        parts.append("")
        parts.append("INCLUDE THESE BLOCK TYPES:")
        parts.append("• text block")
        parts.append("• reflection prompt")
        parts.append("• knowledge check")
        parts.append("• scenario")
        parts.append("• summary")
        parts.append("")
        parts.append("-" * 60)
        parts.append("")

    return "\n".join(parts)


def build_workbook(course_config: dict, lessons: list[dict]) -> str:
    parts = [f"# {course_config['title']} Workbook", ""]
    for idx, lesson in enumerate(lessons, start=1):
        parts.append(f"## Lesson {idx}: {lesson['title']}")
        parts.append("")
        parts.append("### Reflection")
        parts.append("1. What stood out most in this lesson?")
        parts.append("2. How does this issue affect your community?")
        parts.append("3. What civic action could you take based on this lesson?")
        parts.append("")
        parts.append("### Application")
        parts.append("Write one organizing, policy, or leadership step you would take next.")
        parts.append("")
    return "\n".join(parts)


def build_facilitator_guide(course_config: dict, lessons: list[dict]) -> str:
    parts = [f"# {course_config['title']} Facilitator Guide", ""]
    parts.append(f"**Duration:** {course_config.get('duration_minutes', 90)} minutes")
    parts.append("")
    for idx, lesson in enumerate(lessons, start=1):
        parts.append(f"## Lesson {idx}: {lesson['title']}")
        parts.append("")
        parts.append("### Facilitator Goals")
        parts.append("- help learners connect content to Arkansas civic life")
        parts.append("- invite examples from participants' own communities")
        parts.append("- move from awareness to action")
        parts.append("")
        parts.append("### Suggested Flow")
        parts.append("- opening prompt")
        parts.append("- short lesson review")
        parts.append("- discussion")
        parts.append("- activity")
        parts.append("- reflection")
        parts.append("")
    return "\n".join(parts)


def build_quiz_bank(course_config: dict, lessons: list[dict]) -> str:
    parts = [f"# {course_config['title']} Quiz Bank", ""]
    for idx, lesson in enumerate(lessons, start=1):
        parts.append(f"## Lesson {idx}: {lesson['title']}")
        parts.append("")
        for q in range(1, 6):
            parts.append(f"### Question {q}")
            parts.append("What is the most important concept from this lesson?")
            parts.append("")
            parts.append("A. Distractor A")
            parts.append("B. Distractor B")
            parts.append("C. Correct concept")
            parts.append("D. Distractor D")
            parts.append("")
    return "\n".join(parts)


def build_build_plan(course_config: dict, lessons: list[dict]) -> str:
    parts = [f"# {course_config['title']} Build Plan", ""]
    parts.append("## Course Setup")
    parts.append(f"- Title: {course_config['title']}")
    parts.append(f"- Subtitle: {course_config.get('subtitle', '')}")
    parts.append(f"- Duration: {course_config.get('duration_minutes', 90)} minutes")
    parts.append("")
    parts.append("## Recommended Rise Structure")
    parts.append("- cover lesson")
    parts.append("- lesson intro")
    parts.append("- text + scenario + reflection")
    parts.append("- knowledge check")
    parts.append("- summary")
    parts.append("")

    for idx, lesson in enumerate(lessons, start=1):
        parts.append(f"## Lesson {idx}: {lesson['title']}")
        parts.append("")
        parts.append("### Use these Rise blocks")
        parts.append("- text")
        parts.append("- continue divider")
        parts.append("- process")
        parts.append("- flashcards")
        parts.append("- scenario")
        parts.append("- knowledge check")
        parts.append("- quote")
        parts.append("")
        parts.append("### Build Notes")
        parts.append("- start with a local Arkansas example")
        parts.append("- tie abstract ideas to real civic action")
        parts.append("- end with a reflection prompt")
        parts.append("")
    return "\n".join(parts)


def build_scorm_manifest(course_slug: str, lessons: list[dict]) -> str:
    items = []
    resources = []

    for idx, _lesson in enumerate(lessons, start=1):
        items.append(
            f'<item identifier="item_{idx}" identifierref="res_{idx}"><title>Lesson {idx}</title></item>'
        )
        resources.append(
            f'<resource identifier="res_{idx}" type="webcontent" href="lessons/lesson_{idx}.html">'
            f'<file href="lessons/lesson_{idx}.html"/></resource>'
        )

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="{course_slug}" version="1.2"
xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <organizations default="org_1">
    <organization identifier="org_1">
      <title>{course_slug}</title>
      {''.join(items)}
    </organization>
  </organizations>
  <resources>
    {''.join(resources)}
  </resources>
</manifest>
"""


def collect_lessons(course_config: dict) -> list[dict]:
    lessons = []
    course_id = course_config["course_id"]
    course_dir = CONTENT_DIR / course_id

    for chapter in course_config.get("chapters", []):
        chapter_id = chapter["chapter_id"]
        chapter_title = chapter["title"]
        chapter_dir = course_dir / chapter_id / "segments"

        segment_bodies = []

        for seg_name in chapter.get("segments", []):
            seg_path = chapter_dir / seg_name
            if seg_path.exists():
                segment_bodies.append(read_text(seg_path))
            else:
                segment_bodies.append(f"[Missing segment: {seg_name}]")

        lessons.append({
            "chapter_id": chapter_id,
            "title": chapter_title,
            "body": "\n\n".join(segment_bodies)
        })

    return lessons


def export_course(course_config_path: Path) -> None:
    course_config = load_yaml(course_config_path)
    course_id = course_config["course_id"]
    course_slug = slug(course_id)
    course_export_dir = EXPORT_ROOT / course_id
    lessons_dir = course_export_dir / "lessons"
    lessons_dir.mkdir(parents=True, exist_ok=True)

    lessons = collect_lessons(course_config)

    # lesson html files
    for idx, lesson in enumerate(lessons, start=1):
        html = lesson_html(lesson["title"], lesson["body"])
        (lessons_dir / f"lesson_{idx}.html").write_text(html, encoding="utf-8")

    # core assets
    (course_export_dir / "course_manifest.json").write_text(
        json.dumps(course_config, indent=2),
        encoding="utf-8"
    )
    (course_export_dir / "rise_ai_import.txt").write_text(
        build_rise_ai_import(course_config, lessons),
        encoding="utf-8"
    )
    (course_export_dir / "workbook.md").write_text(
        build_workbook(course_config, lessons),
        encoding="utf-8"
    )
    (course_export_dir / "facilitator_guide.md").write_text(
        build_facilitator_guide(course_config, lessons),
        encoding="utf-8"
    )
    (course_export_dir / "quiz_bank.md").write_text(
        build_quiz_bank(course_config, lessons),
        encoding="utf-8"
    )
    (course_export_dir / "build_plan.md").write_text(
        build_build_plan(course_config, lessons),
        encoding="utf-8"
    )
    (course_export_dir / "imsmanifest.xml").write_text(
        build_scorm_manifest(course_slug, lessons),
        encoding="utf-8"
    )

    # launch page
    launch_html = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Course Launch</title></head>
<body>
<h1>Arkansas Civics Course</h1>
<p>Open the lessons folder and launch lesson_1.html to begin.</p>
</body>
</html>
"""
    (course_export_dir / "index.html").write_text(launch_html, encoding="utf-8")

    # zip scorm
    zip_path = EXPORT_ROOT / f"{course_id}_SCORM.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in course_export_dir.rglob("*"):
            if file.is_file():
                zf.write(file, file.relative_to(course_export_dir))

    print(f"Exported course: {course_id}")
    print(f"SCORM: {zip_path}")


def main():
    configs = sorted(CONFIG_DIR.glob("course_*.yaml"))
    if not configs:
        print("No course configs found in config/course_factory/")
        return

    for config_path in configs:
        export_course(config_path)


if __name__ == "__main__":
    main()